#!/usr/bin/env python3
"""2025新版PEP 3-6年级上下册词表生成脚本"""

import csv, os

# === 词表数据 ===
# 格式: (word, meaning, phonetic)

GRADE_DATA = {}

# ========= 三年级上册 =========
GRADE_DATA['三年级上册'] = [
    ("nice", "令人愉快的", "/naɪs/"),
    ("ear", "耳朵", "/ɪə(r)/"),
    ("hand", "手", "/hænd/"),
    ("eye", "眼睛", "/aɪ/"),
    ("mouth", "嘴", "/maʊθ/"),
    ("arm", "胳膊", "/ɑːm/"),
    ("can", "可以", "/kæn/"),
    ("share", "分享", "/ʃeə(r)/"),
    ("smile", "微笑", "/smaɪl/"),
    ("listen", "听；倾听", "/ˈlɪs(ə)n/"),
    ("help", "帮助", "/help/"),
    ("say", "说；讲", "/seɪ/"),
    ("and", "和；与", "/ænd/"),
    ("goodbye", "再见", "/ɡʊdˈbaɪ/"),
    ("toy", "玩具", "/tɔɪ/"),
    ("friend", "朋友", "/frend/"),
    ("good", "好的", "/ɡʊd/"),
    ("mum", "妈妈（口语）", "/mʌm/"),
    ("dad", "爸爸（口语）", "/dæd/"),
    ("grandma", "奶奶；外婆", "/ˈɡrænmɑː/"),
    ("grandpa", "爷爷；外公", "/ˈɡrænpɑː/"),
    ("grandfather", "（外）祖父", "/ˈɡrænfɑːðə(r)/"),
    ("grandmother", "（外）祖母", "/ˈɡrænmʌðə(r)/"),
    ("mother", "母亲；妈妈", "/ˈmʌðə(r)/"),
    ("father", "父亲；爸爸", "/ˈfɑːðə(r)/"),
    ("me", "我", "/miː/"),
    ("sister", "姐；妹", "/ˈsɪstə(r)/"),
    ("family", "家；家庭", "/ˈfæməli/"),
    ("have", "有", "/hæv/"),
    ("big", "大的", "/bɪɡ/"),
    ("cousin", "堂（表）兄弟姐妹", "/ˈkʌz(ə)n/"),
    ("brother", "兄弟", "/ˈbrʌðə(r)/"),
    ("baby", "婴儿", "/ˈbeɪbi/"),
    ("uncle", "舅父；伯父；叔父", "/ˈʌŋk(ə)l/"),
    ("aunt", "姑母；姨母", "/ɑːnt/"),
    ("some", "一些", "/sʌm/"),
    ("small", "小的", "/smɔːl/"),
    ("like", "喜欢", "/laɪk/"),
    ("dog", "狗", "/dɒɡ/"),
    ("pet", "宠物", "/pet/"),
    ("cat", "猫", "/kæt/"),
    ("fish", "鱼", "/fɪʃ/"),
    ("bird", "鸟", "/bɜːd/"),
    ("rabbit", "兔", "/ˈræbɪt/"),
    ("go", "去", "/ɡəʊ/"),
    ("zoo", "动物园", "/zuː/"),
    ("fox", "狐狸", "/fɒks/"),
    ("Miss", "（对女教师的称呼）女士", "/mɪs/"),
    ("panda", "大熊猫", "/ˈpændə/"),
    ("red panda", "小熊猫", "/red ˈpændə/"),
    ("cute", "可爱的", "/kjuːt/"),
    ("monkey", "猴子", "/ˈmʌŋki/"),
    ("tiger", "老虎", "/ˈtaɪɡə(r)/"),
    ("elephant", "大象", "/ˈelɪfənt/"),
    ("lion", "狮子", "/ˈlaɪən/"),
    ("giraffe", "长颈鹿", "/dʒəˈrɑːf/"),
    ("tall", "高的", "/tɔːl/"),
    ("fast", "快的", "/fɑːst/"),
    ("apple", "苹果", "/ˈæp(ə)l/"),
    ("banana", "香蕉", "/bəˈnɑːnə/"),
    ("farm", "农场", "/fɑːm/"),
    ("air", "空气", "/eə(r)/"),
    ("orange", "橙子", "/ˈɒrɪndʒ/"),
    ("grape", "葡萄", "/ɡreɪp/"),
    ("school", "学校", "/skuːl/"),
    ("garden", "花园", "/ˈɡɑːd(ə)n/"),
    ("need", "需要", "/niːd/"),
    ("water", "给……浇水；水", "/ˈwɔːtə(r)/"),
    ("flower", "花", "/ˈflaʊə(r)/"),
    ("grass", "草；草地", "/ɡrɑːs/"),
    ("plant", "种植；植物", "/plɑːnt/"),
    ("new", "新的", "/njuː/"),
    ("tree", "树", "/triː/"),
    ("sun", "太阳", "/sʌn/"),
    ("give", "给", "/ɡɪv/"),
    ("us", "我们", "/ʌs/"),
    ("them", "它们；他们", "/ðem/"),
    ("colour", "颜色", "/ˈkʌlə(r)/"),
    ("green", "绿色；绿色的", "/ɡriːn/"),
    ("red", "红色；红色的", "/red/"),
    ("blue", "蓝色；蓝色的", "/bluː/"),
    ("make", "使出现；做", "/meɪk/"),
    ("purple", "紫色；紫色的", "/ˈpɜːp(ə)l/"),
    ("brown", "棕色；棕色的", "/braʊn/"),
    ("bear", "熊", "/beə(r)/"),
    ("yellow", "黄色（的）", "/ˈjeləʊ/"),
    ("duck", "鸭", "/dʌk/"),
    ("sea", "海洋", "/siː/"),
    ("pink", "粉色；粉色的", "/pɪŋk/"),
    ("draw", "画", "/drɔː/"),
    ("white", "白色（的）", "/waɪt/"),
    ("black", "黑色（的）", "/blæk/"),
    ("old", "（多少）岁；旧的", "/əʊld/"),
    ("five", "五", "/faɪv/"),
    ("year", "年纪；年", "/jɪə(r)/"),
    ("one", "一", "/wʌn/"),
    ("two", "二", "/tuː/"),
    ("three", "三", "/θriː/"),
    ("four", "四", "/fɔː(r)/"),
    ("ten", "十", "/ten/"),
    ("six", "六", "/sɪks/"),
    ("seven", "七", "/ˈsev(ə)n/"),
    ("eight", "八", "/eɪt/"),
    ("nine", "九", "/naɪn/"),
    ("o'clock", "（表示整点）……点钟", "/əˈklɒk/"),
    ("cut", "切块", "/kʌt/"),
    ("piece", "块；片", "/piːs/"),
    ("eat", "吃", "/iːt/"),
    ("cake", "蛋糕", "/keɪk/"),
]

# ========= 三年级下册 =========
GRADE_DATA['三年级下册'] = [
    ("UK", "英国", "/ˌjuːˈkeɪ/"),
    ("Canada", "加拿大", "/ˈkænədə/"),
    ("USA", "美国", "/ˌjuːesˈeɪ/"),
    ("China", "中国", "/ˈtʃaɪnə/"),
    ("she", "她", "/ʃiː/"),
    ("student", "学生", "/ˈstjuːdnt/"),
    ("he", "他", "/hiː/"),
    ("teacher", "教师", "/ˈtiːtʃə(r)/"),
    ("boy", "男孩", "/bɔɪ/"),
    ("girl", "女孩", "/ɡɜːl/"),
    ("where", "在哪里", "/weə(r)/"),
    ("from", "从……来；来自", "/frɒm/"),
    ("today", "今天", "/təˈdeɪ/"),
    ("about", "大约；左右", "/əˈbaʊt/"),
    ("after", "在……后面", "/ˈɑːftə(r)/"),
    ("who", "谁；什么人", "/huː/"),
    ("neighbour", "邻居", "/ˈneɪbə(r)/"),
    ("woman", "成年女子；妇女", "/ˈwʊmən/"),
    ("man", "成年男子；男人", "/mæn/"),
    ("Mr", "先生", "/ˈmɪstə(r)/"),
    ("classmate", "同班同学", "/ˈklɑːsmeɪt/"),
    ("English", "英语的；英语", "/ˈɪŋɡlɪʃ/"),
    ("very", "很；非常", "/ˈveri/"),
    ("welcome", "欢迎", "/ˈwelkəm/"),
    ("new", "新的", "/njuː/"),
    ("pupil", "小学生", "/ˈpjuːpl/"),
    ("back", "回来", "/bæk/"),
    ("we", "我们", "/wiː/"),
    ("class", "同学们；班级", "/klɑːs/"),
    ("has", "（have的第三人称单数）具有", "/hæz/"),
    ("long", "（长度或距离）长的", "/lɒŋ/"),
    ("body", "身体", "/ˈbɒdi/"),
    ("short", "短的；个子矮的", "/ʃɔːt/"),
    ("leg", "腿", "/leg/"),
    ("right", "（意见或判断）准确，恰当", "/raɪt/"),
    ("fat", "肥的；肥胖的", "/fæt/"),
    ("thin", "瘦的", "/θɪn/"),
    ("slow", "缓慢的；慢的", "/sləʊ/"),
    ("love", "喜爱；爱", "/lʌv/"),
    ("tail", "尾；尾巴", "/teɪl/"),
    ("her", "她；她的", "/hɜː(r)/"),
    ("gift", "礼物", "/ɡɪft/"),
    ("picture", "图画；绘画", "/ˈpɪktʃə(r)/"),
    ("card", "贺卡；卡片", "/kɑːd/"),
    ("sing", "唱（歌）；演唱", "/sɪŋ/"),
    ("dance", "跳舞", "/dɑːns/"),
    ("face", "脸；面孔", "/feɪs/"),
    ("all", "所有；全部", "/ɔːl/"),
    ("so", "（表示大小或数量）这么，那么", "/səʊ/"),
    ("talk", "（用某种语言）讲，说", "/tɔːk/"),
    ("song", "歌；歌曲", "/sɒŋ/"),
    ("or", "或；或者；还是", "/ɔː(r)/"),
    ("much", "许多；大量", "/mʌtʃ/"),
    ("bye", "再见；再会", "/baɪ/"),
    ("eraser", "橡皮", "/ɪˈreɪzə(r)/"),
    ("find", "找到；找回", "/faɪnd/"),
    ("ruler", "直尺", "/ˈruːlə(r)/"),
    ("pen", "钢笔", "/pen/"),
    ("pencil", "铅笔", "/ˈpensl/"),
    ("book", "书；书籍", "/bʊk/"),
    ("bag", "包；袋", "/bæɡ/"),
    ("paper", "纸", "/ˈpeɪpə(r)/"),
    ("these", "这些", "/ðiːz/"),
    ("see", "看见", "/siː/"),
    ("smell", "闻（气味）", "/smel/"),
    ("taste", "尝（味道）", "/teɪst/"),
    ("hear", "听见；听到", "/hɪə(r)/"),
    ("touch", "触摸；碰", "/tʌtʃ/"),
    ("sense", "感觉官能（五觉）", "/sens/"),
    ("learn", "学；学习", "/lɜːn/"),
    ("nose", "鼻；鼻子", "/nəʊz/"),
    ("tongue", "舌；舌头", "/tʌŋ/"),
    ("computer", "计算机；电脑", "/kəmˈpjuːtə(r)/"),
    ("breakfast", "早餐；早饭", "/ˈbrekfəst/"),
    ("time", "时间", "/taɪm/"),
    ("bread", "面包", "/bred/"),
    ("egg", "蛋；鸡蛋", "/eɡ/"),
    ("milk", "（牛或羊等的）奶", "/mɪlk/"),
    ("noodle", "（常用复数）面条", "/ˈnuːdl/"),
    ("juice", "果汁", "/dʒuːs/"),
    ("rice", "大米", "/raɪs/"),
    ("meat", "肉", "/miːt/"),
    ("vegetable", "蔬菜", "/ˈvedʒtəbl/"),
    ("healthy", "健康的", "/ˈhelθi/"),
    ("plate", "盘子", "/pleɪt/"),
    ("soup", "汤", "/suːp/"),
    ("fruit", "水果", "/fruːt/"),
    ("colourful", "五彩缤纷的", "/ˈkʌləfl/"),
    ("candy", "糖果", "/ˈkændi/"),
    ("yummy", "很好吃的", "/ˈjʌmi/"),
    ("at", "在（某处）", "/æt/"),
    ("home", "家；住所", "/həʊm/"),
    ("boat", "小船；舟", "/bəʊt/"),
    ("cool", "酷的，绝妙的", "/kuːl/"),
    ("keep", "保有；留着", "/kiːp/"),
    ("ball", "球", "/bɔːl/"),
    ("doll", "玩偶；玩具娃娃", "/dɒl/"),
    ("car", "小汽车；轿车", "/kɑː(r)/"),
    ("on", "在……上", "/ɒn/"),
    ("shelf", "架子", "/ʃelf/"),
    ("in", "在……内；在……中", "/ɪn/"),
    ("box", "盒子", "/bɒks/"),
    ("cap", "帽子", "/kæp/"),
    ("map", "地图", "/mæp/"),
    ("under", "在（或到、通过）……下面", "/ˈʌndə(r)/"),
    ("still", "还是；仍然", "/stɪl/"),
    ("put", "放；安置", "/pʊt/"),
    ("now", "现在", "/naʊ/"),
    ("eleven", "十一", "/ɪˈlevn/"),
    ("twelve", "十二", "/twelv/"),
    ("thirteen", "十三", "/ˌθɜːˈtiːn/"),
    ("fourteen", "十四", "/ˌfɔːˈtiːn/"),
    ("fifteen", "十五", "/ˌfɪfˈtiːn/"),
    ("sixteen", "十六", "/ˌsɪksˈtiːn/"),
    ("seventeen", "十七", "/ˌsevnˈtiːn/"),
    ("eighteen", "十八", "/ˌeɪˈtiːn/"),
    ("nineteen", "十九", "/ˌnaɪnˈtiːn/"),
    ("twenty", "二十", "/ˈtwenti/"),
    ("choose", "选择；挑选", "/tʃuːz/"),
    ("save", "储蓄；攒钱", "/seɪv/"),
    ("spend", "用，花（钱）", "/spend/"),
    ("piggy bank", "猪形储钱罐", "/ˈpɪɡi bæŋk/"),
    ("pay", "付费", "/peɪ/"),
]

# ========= 四年级上册 =========
GRADE_DATA['四年级上册'] = [
    ("PE", "体育（课）", "/ˌpiː ˈiː/"),
    ("job", "工作；职业", "/dʒəʊb/"),
    ("doctor", "医生", "/ˈdɒktə(r)/"),
    ("farmer", "农场主；农民", "/ˈfɑːmə(r)/"),
    ("nurse", "护士", "/nɜːs/"),
    ("worker", "工人", "/ˈwɜːkə(r)/"),
    ("office worker", "公司职员", "/ˈɒfɪs ˈwɜːkə(r)/"),
    ("factory worker", "工厂工人", "/ˈfæktri ˈwɜːkə(r)/"),
    ("busy", "忙碌的", "/ˈbɪzi/"),
    ("tired", "疲倦的", "/ˈtaɪəd/"),
    ("chore", "家庭杂务", "/tʃɔː(r)/"),
    ("cook", "烹饪；煮；厨师", "/kʊk/"),
    ("clean", "打扫；干净的", "/kliːn/"),
    ("room", "房间", "/ruːm/"),
    ("also", "也", "/ˈɔːlsəʊ/"),
    ("look after", "照顾", "/lʊk ˈɑːftə(r)/"),
    ("sweep", "扫", "/swiːp/"),
    ("floor", "地板；地面", "/flɔː(r)/"),
    ("together", "在一起；共同", "/təˈɡeðə(r)/"),
    ("fun", "享乐；乐趣", "/fʌn/"),
    ("helpful", "有帮助的；有用的", "/ˈhelpfl/"),
    ("people", "人；人们", "/ˈpiːpl/"),
    ("child", "儿童；小孩", "/tʃaɪld/"),
    ("his", "他的", "/hɪz/"),
    ("strong", "强壮的", "/strɒŋ/"),
    ("hair", "头发", "/heə(r)/"),
    ("kind", "友好的", "/kaɪnd/"),
    ("quiet", "文静的", "/ˈkwaɪət/"),
    ("best", "最好的", "/best/"),
    ("read", "阅读", "/riːd/"),
    ("Chinese", "中文；中国人；中国的", "/ˌtʃaɪˈniːz/"),
    ("play", "玩耍", "/pleɪ/"),
    ("game", "游戏", "/geɪm/"),
    ("football", "足球运动", "/ˈfʊtbɔːl/"),
    ("both", "两者", "/bəʊθ/"),
    ("basketball", "篮球运动", "/ˈbɑːskɪtbɔːl/"),
    ("always", "总是", "/ˈɔːlweɪz/"),
    ("afternoon", "下午", "/ˌɑːftəˈnuːn/"),
    ("there", "（表示存在或发生）", "/ðeə(r)/"),
    ("playground", "游乐场；操场", "/ˈpleɪɡraʊnd/"),
    ("park", "公园", "/pɑːk/"),
    ("over", "在……的远端（或对面）", "/ˈəʊvə(r)/"),
    ("hospital", "医院", "/ˈhɒspɪtl/"),
    ("shop", "商店", "/ʃɒp/"),
    ("toilet", "厕所；卫生间", "/ˈtɔɪlət/"),
    ("bus", "公共汽车", "/bʌs/"),
    ("stop", "车站；停下", "/stɒp/"),
    ("library", "图书馆", "/ˈlaɪbrəri/"),
    ("sport", "体育运动", "/spɔːt/"),
    ("walk", "散步；行走", "/wɔːk/"),
    ("take", "（与名词连用）；带走", "/teɪk/"),
    ("favourite", "最喜欢的", "/ˈfeɪvərɪt/"),
    ("place", "地方；场所", "/pleɪs/"),
    ("photo", "照片", "/ˈfəʊtəʊ/"),
    ("story", "故事", "/ˈstɔːri/"),
    ("buy", "购买", "/baɪ/"),
    ("firefighter", "消防队员", "/ˈfaɪəfaɪtə(r)/"),
    ("why", "为什么", "/waɪ/"),
    ("driver", "司机", "/ˈdraɪvə(r)/"),
    ("cleaner", "清洁工", "/ˈkliːnə(r)/"),
    ("delivery worker", "快递员", "/dɪˈlɪvəri ˈwɜːkə(r)/"),
    ("police", "警察", "/pəˈliːs/"),
    ("police officer", "警察；警员", "/pəˈliːs ˈɒfɪsə(r)/"),
    ("a lot of", "大量；许多", "/ə lɒt əv/"),
    ("those", "（that的复数形式）那些", "/ðəʊz/"),
    ("bed", "床", "/bed/"),
    ("tell", "讲述；告诉", "/tel/"),
    ("everyone", "每人", "/ˈevriwʌn/"),
    ("volunteer", "志愿者", "/ˌvɒlənˈtɪə(r)/"),
    ("Mrs", "太太；夫人", "/ˈmɪsɪz/"),
    ("speak", "说话；发言", "/spiːk/"),
    ("weather", "天气", "/ˈweðə(r)/"),
    ("sunny", "阳光充足的", "/ˈsʌni/"),
    ("hot", "热的", "/hɒt/"),
    ("bad", "令人不快的；坏的", "/bæd/"),
    ("cold", "冷的", "/kəʊld/"),
    ("windy", "多风的", "/ˈwɪndi/"),
    ("cloudy", "多云的", "/ˈklaʊdi/"),
    ("rainy", "阴雨的", "/ˈreɪni/"),
    ("snowy", "多雪的", "/ˈsnəʊi/"),
    ("cool", "凉爽的", "/kuːl/"),
    ("warm", "温暖的", "/wɔːm/"),
    ("tomorrow", "在明天", "/təˈmɒrəʊ/"),
    ("rain", "下雨；雨", "/reɪn/"),
    ("closed", "关闭的", "/kləʊzd/"),
    ("film", "电影", "/fɪlm/"),
    ("fly", "操纵（飞行器等）；飞", "/flaɪ/"),
    ("kite", "风筝", "/kaɪt/"),
    ("snowman", "雪人", "/ˈsnəʊmæn/"),
    ("their", "他们的；她们的；它们的", "/ðeə(r)/"),
    ("swim", "游泳", "/swɪm/"),
    ("Sydney", "悉尼", "/ˈsɪdni/"),
    ("whose", "谁的", "/huːz/"),
    ("sweater", "毛衣", "/ˈswetə(r)/"),
    ("sock", "短袜", "/sɒk/"),
    ("mine", "我的", "/maɪn/"),
    ("wear", "穿；戴", "/weə(r)/"),
    ("shirt", "衬衫", "/ʃɜːt/"),
    ("coat", "大衣；外套", "/kəʊt/"),
    ("dress", "连衣裙", "/dres/"),
    ("which", "哪一个；哪一些", "/wɪtʃ/"),
    ("season", "季节", "/ˈsiːzn/"),
    ("winter", "冬天", "/ˈwɪntə(r)/"),
    ("snow", "下雪；雪", "/snəʊ/"),
    ("get", "（使）达到，处于", "/get/"),
    ("spring", "春天", "/sprɪŋ/"),
    ("summer", "夏天", "/ˈsʌmə(r)/"),
    ("autumn", "秋天", "/ˈɔːtəm/"),
    ("T-shirt", "T恤衫", "/ˈtiː ʃɜːt/"),
    ("fall", "落下", "/fɔːl/"),
    ("leaf", "叶", "/liːf/"),
    ("glove", "手套", "/ɡlʌv/"),
    ("then", "然后；那时", "/ðen/"),
]

# ========= 四年级下册 =========
GRADE_DATA['四年级下册'] = [
    ("sorry", "对不起", "/ˈsɒri/"),
    ("late", "迟到；迟发生", "/leɪt/"),
    ("hurry up", "快点", "/ˈhʌri ʌp/"),
    ("ready", "准备好", "/ˈredi/"),
    ("rule", "规则", "/ruːl/"),
    ("classroom", "教室", "/ˈklɑːsruːm/"),
    ("light", "灯；光", "/laɪt/"),
    ("blackboard", "黑板", "/ˈblækbɔːd/"),
    ("desk", "书桌", "/desk/"),
    ("chair", "椅子", "/tʃeə(r)/"),
    ("tidy", "整洁的；整理", "/ˈtaɪdi/"),
    ("music", "音乐", "/ˈmjuːzɪk/"),
    ("wall", "墙", "/wɔːl/"),
    ("door", "门", "/dɔː(r)/"),
    ("window", "窗户", "/ˈwɪndəʊ/"),
    ("fan", "风扇", "/fæn/"),
    ("understand", "懂；理解", "/ˌʌndəˈstænd/"),
    ("first", "首先；第一", "/fɜːst/"),
    ("homework", "作业", "/ˈhəʊmwɜːk/"),
    ("watch", "看；手表", "/wɒtʃ/"),
    ("TV", "电视", "/ˌtiːˈviː/"),
    ("newspaper", "报纸", "/ˈnjuːzpeɪpə(r)/"),
    ("handout", "分发", "/ˈhændaʊt/"),
    ("workbook", "练习册", "/ˈwɜːkbʊk/"),
    ("clock", "时钟", "/klɒk/"),
    ("minute", "分钟", "/ˈmɪnɪt/"),
    ("sleep", "睡觉", "/sliːp/"),
    ("kid", "小孩", "/kɪd/"),
    ("dinner", "正餐", "/ˈdɪnə(r)/"),
    ("get up", "起床", "/ɡet ʌp/"),
    ("go to school", "上学", "/ɡəʊ tuː skuːl/"),
    ("go home", "回家", "/ɡəʊ həʊm/"),
    ("go to bed", "上床睡觉", "/ɡəʊ tuː bed/"),
    ("trousers", "裤子", "/ˈtraʊzəz/"),
    ("pair", "一条，一副", "/peə(r)/"),
    ("clothes", "衣服；服装", "/kləʊðz/"),
    ("shorts", "短裤", "/ʃɔːts/"),
    ("jacket", "夹克衫", "/ˈdʒækɪt/"),
    ("skirt", "裙子", "/skɜːt/"),
    ("dear", "天哪", "/dɪə(r)/"),
    ("yours", "你（们）的", "/jɔːz/"),
    ("cow", "奶牛", "/kaʊ/"),
    ("horse", "马", "/hɔːs/"),
    ("sheep", "绵羊", "/ʃiːp/"),
    ("pig", "猪", "/pɪɡ/"),
    ("chicken", "鸡；鸡肉", "/ˈtʃɪkɪn/"),
    ("tomato", "西红柿", "/təˈmɑːtəʊ/"),
    ("carrot", "胡萝卜", "/ˈkærət/"),
    ("potato", "土豆", "/pəˈteɪtəʊ/"),
    ("green bean", "四季豆", "/ɡriːn biːn/"),
    ("farm", "农场", "/fɑːm/"),
    ("scarf", "围巾", "/skɑːf/"),
    ("umbrella", "雨伞", "/ʌmˈbrelə/"),
    ("sunglasses", "太阳镜", "/ˈsʌnɡlɑːsɪz/"),
    ("pretty", "美观的；精致的", "/ˈprɪti/"),
    ("expensive", "昂贵的", "/ɪkˈspensɪv/"),
    ("cheap", "便宜的", "/tʃiːp/"),
    ("try on", "试穿", "/traɪ ɒn/"),
    ("size", "尺码", "/saɪz/"),
    ("how much", "多少钱", "/haʊ mʌtʃ/"),
]

# ========= 五年级上册 =========
GRADE_DATA['五年级上册'] = [
    ("team", "队；（一起工作的）组，班", "/tiːm/"),
    ("player", "运动员；参赛选手", "/ˈpleɪə(r)/"),
    ("him", "他", "/hɪm/"),
    ("lovely", "美丽的；优美的", "/ˈlʌvli/"),
    ("clever", "聪明的；聪颖的", "/ˈklevə(r)/"),
    ("young", "幼小的；年轻的", "/jʌŋ/"),
    ("hard-working", "工作努力的；辛勤的", "/hɑːd ˈwɜːkɪŋ/"),
    ("science", "科学；自然科学", "/ˈsaɪəns/"),
    ("robot", "机器人", "/ˈrəʊbɒt/"),
    ("jump", "跳；跃", "/dʒʌmp/"),
    ("rope", "绳；粗绳", "/rəʊp/"),
    ("piano", "钢琴", "/piˈænəʊ/"),
    ("chess", "国际象棋", "/tʃes/"),
    ("front", "前部", "/frʌnt/"),
    ("easy", "容易的；轻易的", "/ˈiːzi/"),
    ("star", "歌唱（或表演）明星", "/stɑː(r)/"),
    ("wonderful", "精彩的；绝妙的", "/ˈwʌndəfl/"),
    ("Australia", "澳大利亚", "/ɒˈstreɪliə/"),
    ("sad", "悲哀的；难过的", "/sæd/"),
    ("matter", "事情；问题", "/ˈmætə(r)/"),
    ("project", "项目；方案", "/ˈprɒdʒekt/"),
    ("centre", "中心", "/ˈsentə(r)/"),
    ("agree", "同意；赞成", "/əˈɡriː/"),
    ("finish", "完成；做好", "/ˈfɪnɪʃ/"),
    ("Monday", "星期一", "/ˈmʌndeɪ/"),
    ("worried", "担心的；担忧的", "/ˈwʌrid/"),
    ("excited", "激动的；兴奋的", "/ɪkˈsaɪtɪd/"),
    ("wrong", "错误的", "/rɒŋ/"),
    ("angry", "愤怒的；生气的", "/ˈæŋɡri/"),
    ("afraid", "担心；害怕", "/əˈfreɪd/"),
    ("parent", "父亲；母亲", "/ˈpeərənt/"),
    ("ask", "问；询问", "/ɑːsk/"),
    ("move", "搬家；移动", "/muːv/"),
    ("Wednesday", "星期三", "/ˈwenzdeɪ/"),
    ("subject", "科目；学科", "/ˈsʌbdʒɪkt/"),
    ("Tuesday", "星期二", "/ˈtjuːzdeɪ/"),
    ("Friday", "星期五", "/ˈfraɪdeɪ/"),
    ("because", "因为", "/bɪˈkɒz/"),
    ("Thursday", "星期四", "/ˈθɜːzdeɪ/"),
    ("start", "开始", "/stɑːt/"),
    ("usually", "通常地；经常地", "/ˈjuːʒuəli/"),
    ("weekend", "周末", "/ˌwiːkˈend/"),
    ("sometimes", "有时；间或", "/ˈsʌmtaɪmz/"),
    ("Saturday", "星期六", "/ˈsætədeɪ/"),
    ("Sunday", "星期日", "/ˈsʌndeɪ/"),
    ("lesson", "课；一节课", "/ˈlesn/"),
    ("evening", "晚上；傍晚", "/ˈiːvnɪŋ/"),
    ("answer", "答复；回答", "/ˈɑːnsə(r)/"),
    ("ping-pong", "乒乓球", "/ˈpɪŋ pɒŋ/"),
    ("night", "夜；夜晚", "/naɪt/"),
    ("visit", "看望；拜访；参观", "/ˈvɪzɪt/"),
    ("grandparent", "祖父；祖母；外祖父；外祖母", "/ˈɡrænpeərənt/"),
    ("stay", "待；保持", "/steɪ/"),
    ("should", "（提出或征询建议）该，可以", "/ʃʊd/"),
    ("flu", "流行性感冒；流感", "/fluː/"),
    ("else", "其他的；别的", "/els/"),
    ("exercise", "锻炼；训练", "/ˈeksəsaɪz/"),
    ("enough", "足够的；充足的", "/ɪˈnʌf/"),
    ("if", "如果；假若", "/ɪf/"),
    ("habit", "习惯", "/ˈhæbɪt/"),
    ("show", "（电视或广播）节目", "/ʃəʊ/"),
    ("phone", "电话；电话机", "/fəʊn/"),
    ("rest", "休息；放松", "/rest/"),
    ("check", "查看；查明", "/tʃek/"),
    ("less", "（与不可数名词连用）较少的", "/les/"),
    ("brush", "（用刷子）刷净", "/brʌʃ/"),
    ("tooth", "牙；齿", "/tuːθ/"),
    ("twice", "两次；两遍", "/twaɪs/"),
    ("hour", "小时", "/ˈaʊə(r)/"),
    ("free", "没有安排活动的；空闲的", "/friː/"),
    ("hungry", "感到饿的", "/ˈhʌŋɡri/"),
    ("beef", "牛肉", "/biːf/"),
    ("ice cream", "（一份）冰激凌", "/ˌaɪs ˈkriːm/"),
    ("little", "少许；一点", "/ˈlɪtl/"),
    ("dumpling", "饺子；汤圆", "/ˈdʌmplɪŋ/"),
    ("tea", "茶叶；茶", "/tiː/"),
    ("hamburger", "汉堡包", "/ˈhæmbɜːɡə(r)/"),
    ("coconut", "椰子", "/ˈkəʊkənʌt/"),
    ("interesting", "有趣的；有吸引力的", "/ˈɪntrəstɪŋ/"),
    ("seed", "种子；籽", "/siːd/"),
    ("pull", "拔出；抽出", "/pʊl/"),
    ("stem", "（花草的）茎", "/stem/"),
    ("root", "根；根茎", "/ruːt/"),
    ("lotus", "莲属植物", "/ˈləʊtəs/"),
    ("lake", "湖；湖泊", "/leɪk/"),
    ("world", "世界；地球", "/wɜːld/"),
    ("round", "圆形的；环形的", "/raʊnd/"),
    ("different", "不同的", "/ˈdɪfrənt/"),
    ("way", "方法；手段", "/weɪ/"),
    ("river", "河；江", "/ˈrɪvə(r)/"),
    ("nature", "自然界；大自然", "/ˈneɪtʃə(r)/"),
    ("waterfall", "瀑布", "/ˈwɔːtəfɔːl/"),
    ("forest", "森林；林区", "/ˈfɒrɪst/"),
    ("famous", "著名的；出名的", "/ˈfeɪməs/"),
    ("mountain", "高山；山岳", "/ˈmaʊntən/"),
    ("wind", "风；气流", "/wɪnd/"),
    ("trip", "（尤指短程往返的）旅行", "/trɪp/"),
    ("dangerous", "有危险的；不安全的", "/ˈdeɪndʒərəs/"),
    ("heavy", "程度大的；严重的", "/ˈhevi/"),
    ("hotel", "旅馆；旅社", "/həʊˈtel/"),
    ("close", "关；关闭", "/kləʊz/"),
    ("raincoat", "雨衣", "/ˈreɪnkəʊt/"),
    ("worry", "担心；担忧", "/ˈwʌri/"),
    ("fine", "晴朗的", "/faɪn/"),
    ("fog", "雾", "/fɒɡ/"),
    ("flood", "洪水；水灾", "/flʌd/"),
    ("fire", "火；火灾", "/ˈfaɪə(r)/"),
    ("know", "知道；了解", "/nəʊ/"),
    ("before", "在……之前", "/bɪˈfɔː(r)/"),
    ("bring", "带……到某处；带来", "/brɪŋ/"),
]

# ========= 五年级下册 =========
GRADE_DATA['五年级下册'] = [
    ("eat breakfast", "吃早饭", ""),
    ("have class", "上课", ""),
    ("play sports", "进行体育运动", ""),
    ("do morning exercises", "做早操", ""),
    ("eat dinner", "吃晚饭", ""),
    ("clean my room", "打扫我的房间", ""),
    ("go for a walk", "散步", ""),
    ("go shopping", "去买东西；购物", ""),
    ("take", "学习；上（课）", "/teɪk/"),
    ("dancing", "跳舞；舞蹈", "/ˈdɑːnsɪŋ/"),
    ("take a dancing class", "上舞蹈课", ""),
    ("exercise", "活动；运动", "/ˈeksəsaɪz/"),
    ("when", "什么时候；何时", "/wen/"),
    ("Spain", "西班牙", "/speɪn/"),
    ("p.m.", "午后；下午", "/ˌpiːˈem/"),
    ("shop", "去买东西；购物", "/ʃɒp/"),
    ("work", "工作", "/wɜːk/"),
    ("last", "上一个的；刚过去的", "/lɑːst/"),
    ("sound", "听起来好像", "/saʊnd/"),
    ("play", "戏剧；剧本", "/pleɪ/"),
    ("letter", "信", "/ˈletə(r)/"),
    ("live", "居住", "/lɪv/"),
    ("island", "岛", "/ˈaɪlənd/"),
    ("cave", "山洞；洞穴", "/keɪv/"),
    ("win", "获胜", "/wɪn/"),
    ("spring", "春天", "/sprɪŋ/"),
    ("summer", "夏天", "/ˈsʌmə(r)/"),
    ("autumn", "秋天", "/ˈɔːtəm/"),
    ("winter", "冬天", "/ˈwɪntə(r)/"),
    ("season", "季节", "/ˈsiːzn/"),
    ("picnic", "野餐", "/ˈpɪknɪk/"),
    ("go on a picnic", "去野餐", ""),
    ("go swimming", "去游泳", ""),
    ("pick apples", "摘苹果", ""),
    ("make a snowman", "堆雪人", ""),
    ("snow", "雪", "/snəʊ/"),
    ("vacation", "假期", "/veɪˈkeɪʃn/"),
    ("pink", "粉色；粉色的", "/pɪŋk/"),
    ("leaf", "叶子", "/liːf/"),
    ("paint", "用颜料绘画", "/peɪnt/"),
    ("pick", "摘；采集", "/pɪk/"),
    ("January", "一月", "/ˈdʒænjuəri/"),
    ("February", "二月", "/ˈfebruəri/"),
    ("March", "三月", "/mɑːtʃ/"),
    ("April", "四月", "/ˈeɪprəl/"),
    ("May", "五月", "/meɪ/"),
    ("June", "六月", "/dʒuːn/"),
    ("July", "七月", "/dʒuˈlaɪ/"),
    ("August", "八月", "/ˈɔːɡəst/"),
    ("September", "九月", "/sepˈtembə(r)/"),
    ("October", "十月", "/ɒkˈtəʊbə(r)/"),
    ("November", "十一月", "/nəʊˈvembə(r)/"),
    ("December", "十二月", "/dɪˈsembə(r)/"),
    ("few", "不多；很少", "/fjuː/"),
    ("a few", "一些", ""),
    ("thing", "事情", "/θɪŋ/"),
    ("meet", "集会；开会", "/miːt/"),
    ("sports meet", "运动会", ""),
    ("year", "年", "/jɪə(r)/"),
    ("plant", "种植", "/plɑːnt/"),
    ("contest", "比赛；竞赛", "/ˈkɒntest/"),
    ("the Great Wall", "长城", ""),
    ("national", "国家的", "/ˈnæʃnəl/"),
    ("National Day", "国庆日", ""),
    ("American", "美国的", "/əˈmerɪkən/"),
    ("Thanksgiving", "感恩节", "/ˌθæŋksˈɡɪvɪŋ/"),
    ("Christmas", "圣诞节", "/ˈkrɪsməs/"),
    ("riddle", "谜；谜语", "/ˈrɪdl/"),
    ("act", "扮演", "/ækt/"),
    ("first", "第一（的）", "/fɜːst/"),
    ("second", "第二（的）", "/ˈsekənd/"),
    ("third", "第三（的）", "/θɜːd/"),
    ("fourth", "第四（的）", "/fɔːθ/"),
    ("fifth", "第五（的）", "/fɪfθ/"),
    ("twelfth", "第十二（的）", "/twelfθ/"),
    ("twentieth", "第二十（的）", "/ˈtwentiəθ/"),
    ("twenty-first", "第二十一（的）", ""),
    ("twenty-third", "第二十三（的）", ""),
    ("thirtieth", "第三十（的）", "/ˈθɜːtiəθ/"),
    ("other", "其他", "/ˈʌðə(r)/"),
    ("special", "特殊的；特别的", "/ˈspeʃl/"),
    ("festival", "节日", "/ˈfestɪvl/"),
    ("kitten", "小猫", "/ˈkɪtn/"),
    ("diary", "日记", "/ˈdaɪəri/"),
    ("noise", "声音；响声；噪音", "/nɔɪz/"),
    ("fur", "（某些动物的）浓密的软毛", "/fɜː(r)/"),
    ("open", "开着的", "/ˈəʊpən/"),
    ("mine", "我的", "/maɪn/"),
    ("yours", "你（们）的", "/jɔːz/"),
    ("his", "他的", "/hɪz/"),
    ("hers", "她的", "/hɜːz/"),
    ("theirs", "他们的；她们的；它们的", "/ðeəz/"),
    ("ours", "我们的", "/ˈaʊəz/"),
    ("climbing", "（正在）攀登；攀爬", "/ˈklaɪmɪŋ/"),
    ("eating", "（正在）吃", "/ˈiːtɪŋ/"),
    ("playing", "（正在）玩耍", "/ˈpleɪɪŋ/"),
    ("jumping", "（正在）跳", "/ˈdʒʌmpɪŋ/"),
    ("drinking", "（正在）喝（水）", "/ˈdrɪŋkɪŋ/"),
    ("sleeping", "（正在）睡觉", "/ˈsliːpɪŋ/"),
    ("each", "每一；各个", "/iːtʃ/"),
    ("excited", "兴奋的；激动的", "/ɪkˈsaɪtɪd/"),
    ("exhibition", "展览", "/ˌeksɪˈbɪʃn/"),
    ("teach", "教", "/tiːtʃ/"),
    ("sure", "（表示同意）当然", "/ʃʊə(r)/"),
    ("Canadian", "加拿大的", "/kəˈneɪdiən/"),
    ("Spanish", "西班牙的", "/ˈspænɪʃ/"),
    ("its", "它的", "/ɪts/"),
    ("bamboo", "竹子", "/ˌbæmˈbuː/"),
    ("doing morning exercises", "（正在）做早操", ""),
    ("eating lunch", "（正在）吃午饭", ""),
    ("reading a book", "（正在）看书", ""),
    ("listening to music", "（正在）听音乐", ""),
    ("keep", "保持某种状态", "/kiːp/"),
    ("keep to the right", "靠右", ""),
    ("keep your desk clean", "保持你的课桌干净", ""),
    ("talk quietly", "小声讲话", ""),
    ("turn", "顺序", "/tɜːn/"),
    ("take turns", "按顺序来", ""),
]

# ========= 六年级上册 =========
GRADE_DATA['六年级上册'] = [
    ("science", "科学", "/ˈsaɪəns/"),
    ("museum", "博物馆", "/mjuˈziːəm/"),
    ("post office", "邮局", ""),
    ("bookstore", "书店", "/ˈbʊkstɔː(r)/"),
    ("interesting", "有趣的", "/ˈɪntrəstɪŋ/"),
    ("Italian", "意大利的", "/ɪˈtæliən/"),
    ("restaurant", "餐馆", "/ˈrestrɒnt/"),
    ("pizza", "比萨饼", "/ˈpiːtsə/"),
    ("street", "大街；街道", "/striːt/"),
    ("get", "到达", "/ɡet/"),
    ("crossing", "十字路口", "/ˈkrɒsɪŋ/"),
    ("turn", "转弯", "/tɜːn/"),
    ("left", "左", "/left/"),
    ("straight", "笔直地", "/streɪt/"),
    ("right", "右", "/raɪt/"),
    ("follow", "跟着", "/ˈfɒləʊ/"),
    ("far", "较远的", "/fɑː(r)/"),
    ("tell", "告诉", "/tel/"),
    ("GPS", "全球（卫星）定位系统", ""),
    ("gave", "提供；交给", "/ɡeɪv/"),
    ("feature", "特点", "/ˈfiːtʃə(r)/"),
    ("on foot", "步行", ""),
    ("by", "（表示方式）乘", "/baɪ/"),
    ("bus", "公共汽车", "/bʌs/"),
    ("plane", "飞机", "/pleɪn/"),
    ("taxi", "出租汽车", "/ˈtæksi/"),
    ("ship", "（大）船", "/ʃɪp/"),
    ("subway", "地铁", "/ˈsʌbweɪ/"),
    ("train", "火车", "/treɪn/"),
    ("slow down", "慢下来", ""),
    ("early", "早到的", "/ˈɜːli/"),
    ("helmet", "头盔", "/ˈhelmɪt/"),
    ("must", "必须", "/mʌst/"),
    ("attention", "注意", "/əˈtenʃn/"),
    ("pay attention to", "注意", ""),
    ("traffic", "交通", "/ˈtræfɪk/"),
    ("traffic lights", "交通信号灯", ""),
    ("Munich", "慕尼黑（德国城市）", ""),
    ("Germany", "德国", "/ˈdʒɜːməni/"),
    ("Alaska", "阿拉斯加州", "/əˈlæskə/"),
    ("sled", "雪橇", "/sled/"),
    ("fast", "快的", "/fɑːst/"),
    ("ferry", "轮渡", "/ˈferi/"),
    ("Scotland", "苏格兰", "/ˈskɒtlənd/"),
    ("visit", "拜访", "/ˈvɪzɪt/"),
    ("see a film", "看电影", ""),
    ("take a trip", "去旅行", ""),
    ("supermarket", "超市", "/ˈsuːpəmɑːkɪt/"),
    ("tonight", "在今晚", "/təˈnaɪt/"),
    ("tomorrow", "明天", "/təˈmɒrəʊ/"),
    ("next week", "下周", ""),
    ("dictionary", "词典", "/ˈdɪkʃənri/"),
    ("comic", "滑稽的", "/ˈkɒmɪk/"),
    ("comic book", "（儿童的）连环画册", ""),
    ("word", "单词", "/wɜːd/"),
    ("word book", "单词书", ""),
    ("postcard", "明信片", "/ˈpəʊstkɑːd/"),
    ("space", "太空", "/speɪs/"),
    ("travel", "（尤指长途）旅行", "/ˈtrævl/"),
    ("half", "一半", "/hɑːf/"),
    ("price", "价格", "/praɪs/"),
    ("Mid-Autumn Festival", "中秋节", ""),
    ("mooncake", "月饼", ""),
    ("poem", "诗", "/ˈpəʊɪm/"),
    ("moon", "月亮", "/muːn/"),
    ("studies", "学习", "/ˈstʌdiz/"),
    ("puzzle", "谜", "/ˈpʌzl/"),
    ("hiking", "远足", "/ˈhaɪkɪŋ/"),
    ("pen pal", "笔友", ""),
    ("hobby", "业余爱好", "/ˈhɒbi/"),
    ("jasmine", "茉莉", "/ˈdʒæzmɪn/"),
    ("idea", "想法；主意", "/aɪˈdɪə/"),
    ("Canberra", "堪培拉（澳大利亚首都）", ""),
    ("amazing", "令人惊奇的", "/əˈmeɪzɪŋ/"),
    ("shall", "表示征求意见", "/ʃæl/"),
    ("goal", "射门", "/ɡəʊl/"),
    ("join", "加入", "/dʒɔɪn/"),
    ("club", "俱乐部", "/klʌb/"),
    ("share", "分享", "/ʃeə(r)/"),
    ("factory", "工厂", "/ˈfæktri/"),
    ("worker", "工人", "/ˈwɜːkə(r)/"),
    ("postman", "邮递员", "/ˈpəʊstmən/"),
    ("businessman", "商人；企业家", "/ˈbɪznəsmæn/"),
    ("fisherman", "渔民", "/ˈfɪʃəmən/"),
    ("scientist", "科学家", "/ˈsaɪəntɪst/"),
    ("pilot", "飞行员", "/ˈpaɪlət/"),
    ("coach", "教练", "/kəʊtʃ/"),
    ("country", "国家", "/ˈkʌntri/"),
    ("head teacher", "校长", ""),
    ("sea", "大海", "/siː/"),
    ("university", "大学", "/ˌjuːnɪˈvɜːsəti/"),
    ("gym", "体育馆", "/dʒɪm/"),
    ("reporter", "记者", "/rɪˈpɔːtə(r)/"),
    ("use", "使用", "/juːz/"),
    ("type", "打字", "/taɪp/"),
    ("quickly", "迅速地", "/ˈkwɪkli/"),
    ("secretary", "秘书", "/ˈsekrətri/"),
    ("angry", "生气的", "/ˈæŋɡri/"),
    ("afraid", "害怕", "/əˈfreɪd/"),
    ("sad", "难过的", "/sæd/"),
    ("worried", "担心的；发愁的", "/ˈwʌrid/"),
    ("happy", "高兴的", "/ˈhæpi/"),
    ("see a doctor", "看病", ""),
    ("more", "更多的", "/mɔː(r)/"),
    ("deep", "深的", "/diːp/"),
    ("breath", "呼吸", "/breθ/"),
    ("take a deep breath", "深深吸一口气", ""),
    ("count", "数数", "/kaʊnt/"),
    ("count to ten", "数到十", ""),
    ("chase", "追赶", "/tʃeɪs/"),
    ("mice", "老鼠", "/maɪs/"),
    ("hurt", "（使）受伤", "/hɜːt/"),
    ("ill", "有病；不舒服", "/ɪl/"),
    ("should", "应该", "/ʃʊd/"),
    ("feel", "觉得；感到", "/fiːl/"),
    ("well", "健康；身体好", "/wel/"),
    ("sit", "坐", "/sɪt/"),
    ("ant", "蚂蚁", "/ænt/"),
    ("stuck", "陷住；无法移动", "/stʌk/"),
    ("mud", "泥", "/mʌd/"),
    ("everyone", "每人", "/ˈevriwʌn/"),
]

# ========= 六年级下册 =========
GRADE_DATA['六年级下册'] = [
    ("younger", "更年轻的", ""),
    ("older", "更年长的", ""),
    ("taller", "更高的", ""),
    ("shorter", "更矮的；更短的", ""),
    ("longer", "更长的", ""),
    ("thinner", "更瘦的", ""),
    ("heavier", "更重的", ""),
    ("bigger", "更大的", ""),
    ("smaller", "更小的", ""),
    ("stronger", "更强壮的", ""),
    ("than", "比", "/ðæn/"),
    ("both", "两个都", "/bəʊθ/"),
    ("kilogram", "千克；公斤", "/ˈkɪləɡræm/"),
    ("metre", "米", "/ˈmiːtə(r)/"),
    ("dinosaur", "恐龙", "/ˈdaɪnəsɔː(r)/"),
    ("hall", "大厅", "/hɔːl/"),
    ("countryside", "乡村", "/ˈkʌntrisaɪd/"),
    ("lower", "更低的", ""),
    ("shadow", "阴影；影子", "/ˈʃædəʊ/"),
    ("smarter", "更聪明的", ""),
    ("become", "开始变得；变成", "/bɪˈkʌm/"),
    ("cleaned", "打扫", ""),
    ("stayed", "停留；待", ""),
    ("washed", "洗", ""),
    ("watched", "看", ""),
    ("had", "患病；得病", "/hæd/"),
    ("had a cold", "感冒", ""),
    ("slept", "睡觉", ""),
    ("read", "读", "/red/"),
    ("saw", "看见", ""),
    ("yesterday", "昨天", "/ˈjestədeɪ/"),
    ("drank", "喝", ""),
    ("magazine", "杂志", "/ˌmæɡəˈziːn/"),
    ("better", "更好的", "/ˈbetə(r)/"),
    ("faster", "更快的", ""),
    ("fixed", "修理", ""),
    ("broken", "破损的", "/ˈbrəʊkən/"),
    ("lamp", "台灯", "/læmp/"),
    ("loud", "喧闹的；大声的", "/laʊd/"),
    ("enjoy", "享受……乐趣", "/ɪnˈdʒɔɪ/"),
    ("went", "去", ""),
    ("camp", "野营", "/kæmp/"),
    ("went camping", "（尤指在假日）野营", ""),
    ("fishing", "钓鱼", "/ˈfɪʃɪŋ/"),
    ("went fishing", "去钓鱼", ""),
    ("rode", "骑（马；自行车）", ""),
    ("hurt", "（使）受伤", "/hɜːt/"),
    ("ate", "吃", ""),
    ("took", "拍照", ""),
    ("took pictures", "照相", ""),
    ("bought", "买", ""),
    ("gift", "礼物", "/ɡɪft/"),
    ("fell", "摔倒", ""),
    ("off", "从（某处）落下", "/ɒf/"),
    ("Labour Day", "劳动节", ""),
    ("mule", "骡子", "/mjuːl/"),
    ("Turpan", "吐鲁番", ""),
    ("could", "能", "/kʊd/"),
    ("till", "直到", "/tɪl/"),
    ("beach", "海滩；沙滩", "/biːtʃ/"),
    ("basket", "篮；筐", "/ˈbɑːskɪt/"),
    ("part", "角色", "/pɑːt/"),
    ("licked", "舔", ""),
    ("laughed", "笑", ""),
    ("dining hall", "饭厅", ""),
    ("grass", "草坪", "/ɡrɑːs/"),
    ("gym", "体育馆", "/dʒɪm/"),
    ("ago", "以前", "/əˈɡəʊ/"),
    ("cycling", "骑自行车运动", "/ˈsaɪklɪŋ/"),
    ("go cycling", "去骑自行车", ""),
    ("ice-skate", "滑冰", ""),
    ("badminton", "羽毛球运动", "/ˈbædmɪntən/"),
    ("Internet", "互联网", "/ˈɪntənet/"),
    ("active", "积极的；活跃的", "/ˈæktɪv/"),
    ("race", "赛跑", "/reɪs/"),
    ("nothing", "没有什么", "/ˈnʌθɪŋ/"),
    ("thought", "想", ""),
    ("felt", "感觉", ""),
    ("cheetah", "猎豹", "/ˈtʃiːtə/"),
    ("woke", "醒", ""),
    ("dream", "梦", "/driːm/"),
]

# === 生成 CSV ===
OUT_DIR = 'd:/code/recite-app'
HEADER = ['word', 'meaning', 'phonetic', 'example', 'example_cn']

total = 0
for grade_name, words in GRADE_DATA.items():
    fname = f'grade_{grade_name}.csv'
    fpath = os.path.join(OUT_DIR, fname)
    with open(fpath, 'w', encoding='utf-8', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(HEADER)
        for w, m, p in words:
            writer.writerow([w, m, p, '', ''])
    print(f'{fname}: {len(words)} words')
    total += len(words)

print(f'\nTotal: {total} words across {len(GRADE_DATA)} grade files')
print('Done!')
